Insert into estado (nome, uf) values ('Acre', 'AC');
Insert into estado (nome, uf) values ('Alagoas', 'AL');
Insert into estado (nome, uf) values ('Amapá', 'AP');
Insert into estado (nome, uf) values ('Amazonas', 'AM');
Insert into estado (nome, uf) values ('Bahia', 'BA');
Insert into estado (nome, uf) values ('Ceará', 'CE');
Insert into estado (nome, uf) values ('Distrito Federal', 'DF');
Insert into estado (nome, uf) values ('Espírito Santo', 'ES');
Insert into estado (nome, uf) values ('Goiás', 'GO');
Insert into estado (nome, uf) values ('Maranhão', 'MA');
Insert into estado (nome, uf) values ('Mato Grosso', 'MT');
Insert into estado (nome, uf) values ('Mato Grosso do Sul', 'MS');
Insert into estado (nome, uf) values ('Minas Gerais', 'MG');
Insert into estado (nome, uf) values ('Pará', 'PA');
Insert into estado (nome, uf) values ('Paraíba', 'PB');
Insert into estado (nome, uf) values ('Paraná', 'PR');
Insert into estado (nome, uf) values ('Pernambuco', 'PE');
Insert into estado (nome, uf) values ('Piauí', 'PI');
Insert into estado (nome, uf) values ('Rio de Janeiro', 'RJ');
Insert into estado (nome, uf) values ('Rio Grande do Norte', 'RN');
Insert into estado (nome, uf) values ('Rio Grande do Sul', 'RS');
Insert into estado (nome, uf) values ('Rondônia', 'RO');
Insert into estado (nome, uf) values ('Roraima', 'RR');
Insert into estado (nome, uf) values ('Santa Catarina', 'SC');
Insert into estado (nome, uf) values ('São Paulo', 'SP');
Insert into estado (nome, uf) values ('Sergipe', 'SE');
Insert into estado (nome, uf) values ('Tocantins', 'TO');